import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { ShoppingCartProvider } from "./_context/ShoppingCartContext";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ShoppingCartProvider>
        <html lang="en" suppressHydrationWarning>
          <body
            className={`${roboto.variable} antialiased overflow-x-hidden`}
            cz-shortcut-listen="true"
          >
            <Header />
            {children}
            <Footer />
          </body>
        </html>
      </ShoppingCartProvider>
    </ClerkProvider>
  );
}
